[package]
name = "server"
version = "0.1.0"
authors = ["Clark Kent<clark@krypton.com>"]
edition = "2018"

[dependencies]
actix-files = "0.2.*"
actix-rt = "1.0.*"
actix-web = "2.0.*"
clap = "2.33.*"
env_logger = "0.7"
log = "0.4"
