[package]
name = "spa"
version = "0.1.0"
authors = ["Clark Kent<clark@krypton.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
yew-router = "0.12"
yew = "0.15"
wasm-bindgen = "^0.2"
